apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
        - name: api-rest
          image: "kwaark/api_rest:v1.0"
          env:
            - name: BROKER_URL
              value: "kafka:9092"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"