apiVersion: v1
kind: Service
metadata:
  name: api-rest
  labels:
    app: api-rest
spec:
  type: NodePort
  ports:
    - name: http
      port: 443
      targetPort: 8000
  selector:
    app: api-rest